---
- name: Instalare dinamică tehnologii DevOps conform configurării
  hosts: all
  become: true

  tasks:
    - name: Încarcă variabilele din vars.json
      include_vars:
        file: config/vars.json
        name: config_data

    - name: Extrage lista de nume ale tehnologiilor
      set_fact:
        tools_list: "{{ config_data.install_tools | map(attribute='name') | list }}"

    - name: Actualizează indecșii pachetelor apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # 1. DOCKER
    - name: Instalează Docker Engine dacă este cerut
      apt:
        name: docker.io
        state: present
      when: "'docker' in tools_list"

    # 2. PYTHON
    - name: Instalează Python 3 și Pip dacă sunt cerute
      apt:
        name:
          - python3
          - python3-pip
        state: present
      when: "'python' in tools_list"

    # 3. MYSQL
    - name: Instalează MySQL Server dacă este cerut
      apt:
        name: mysql-server
        state: present
      when: "'mysql' in tools_list"

    # 4. NODE.JS
    - name: Instalează Node.js dacă este cerut
      apt:
        name: nodejs
        state: present
      when: "'nodejs' in tools_list"

    # 5. JAVA (Bonus)
    - name: Instalează OpenJDK 17 dacă este cerut
      apt:
        name: openjdk-17-jdk
        state: present
      when: "'java' in tools_list"